### ISSUE TITLE
Function Calling: Support optional calling

### ISSUE THREAD

**Issue by keyboardAnt** [minimaxir/simpleaichat#26]
Allow keeping the request's [`function_call`](https://github.com/minimaxir/simpleaichat/blob/ffc0a75f88f7aaf1bc487ccae471d268ac5f4779/simpleaichat/chatgpt.py#L63) empty so that the model won't be enforced to call one of the given [`functions`](https://github.com/minimaxir/simpleaichat/blob/ffc0a75f88f7aaf1bc487ccae471d268ac5f4779/simpleaichat/chatgpt.py#L64). An example use case is in OpenAI Cookbook's [How to Call Functions with Chat Models](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb) tutorial ("Don't make assumptions about what values to plug into functions. Ask for clarification if a user request is ambiguous.").

**Comment by minimaxir** [comment]
The intent of the current implementation of function calling is _only_ structured data I/O, so if an `output_schema` is specified then we know with certainty that we want that function to be called as the output.

The PR doesn't hurt since maybe I'll have to implement selection function calling but I may reconsider.
